[package]
name = "mlkem"
version = "0.0.1"
edition = "2021"
authors = ["Emanuele Civini <emanuelecivini@gmail.com>"]


[lib]
name = "mlkem"
path = "src/lib.rs"

[dependencies]
sha3 = "0.10.8"
rand = "0.8.5"
rand_chacha = "0.3.1"
clap = "4.5.0"
base64 = "0.21.7"